# -*- coding: utf-8 -*-
"""task3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/kumar1984/task3-py.d52fca3c-7b02-4bbd-8580-64fc40825e53.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260519/auto/storage/goog4_request%26X-Goog-Date%3D20260519T132017Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7302aa4a5d5b4566698390b5ec4f82af0b296017f0af0290807745da2a8efa8409a803c6fa8309d434396982eefc5605d3e36d775e01d6390838507f7d1a9d4b24fe4fc47ca7afae13878af02a2e6668c3bb7c21a78abdae6a383bf8336ad40c15c7073a6586a35c636abf7d848d9cbea5f066826c8cac60d9120b9ee22dc2f8946b95a9f85e88dbe286dc7e94507988fc7f1c55409a7046e0e91b0bfbcf6a28a618683b0b3f5dfba036511d9093001b1e1446728419382b4356a7496c6a3a8923827030ed91d33de76a3b9bd0796ececbeca38062475d1cefe3bd442f314b2e7b0958c09fe3a049d46c07d83fa7ba8864eb8554264410a87c4b7c58b83f37ce
"""

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification
)

model_name = "distilbert-base-cased"

tokenizer = DistilBertTokenizerFast.from_pretrained(model_name)

model = DistilBertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

print("Tokenizer and Model Loaded Successfully")

"""I chose the DistilBERT model because it is a compact and faster version of the original BERT model while still maintaining strong performance in natural language processing tasks. DistilBERT requires less computational power and memory, which makes it suitable for training and testing in limited-resource environments. In this task, the Hugging Face Transformers library was used to load the tokenizer and the pre-trained sequence classification model. The model was configured with two output labels for classification purposes. DistilBERT is widely used for text classification, sentiment analysis, and other NLP applications because it provides efficient performance with reduced model size. This model is easy to implement and helps achieve faster execution compared to larger transformer models."""