# -*- coding: utf-8 -*-
"""task5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/kumar1984/task5-py.553c07e9-9a7b-409b-8c85-1b18f24c13b5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260519/auto/storage/goog4_request%26X-Goog-Date%3D20260519T115644Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7efe5513f92d00b01a39f883e839003fa08ceef19ba05ca56805c1abe6d93f23fd6784318de9dc2c6cd9f13b26adc3b815c04c45acc1c2425a36b413cb793cba4b6cb229d61787b61b1273c0a54ffc7e915a2dc973c1ec8216864873599d4edf39b9c143e2f22b5e7be16c301dc3d394c50b36177c27cf81673c507362f96c48f55c045df58f8217df7e0d4980c75875b84b199ee5202888eb408ab3e929e97d4e81a35977b16b67cb037ab7e0b4ac22ccf74de10f42205a3a6337460dd7306167a6d7d4df12d426aaf0f8cddd70a449f3aae3f445615c51876f15a39fb844cec7d4fc59b1507906985632f0e1b37b47d6b7f072d1ecbd963d100fed17b5eab7
"""

import torch
import wandb
import json

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import accuracy_score, f1_score, classification_report
from datasets import Dataset

# Model name
model_name = "distilbert-base-cased"

# Tokenizer
tokenizer = DistilBertTokenizerFast.from_pretrained(model_name)

# Model
model = DistilBertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

print("Tokenizer and Model Loaded Successfully")

# WandB login
wandb.init(
    project="mlops-assignment2",
    name="distilbert-task5"
)

print("WandB Initialized Successfully")

# Metrics function
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="weighted")
    }

print("Metrics Function Created Successfully")

# Dummy dataset
dummy_data = {
    "input_ids": [[101, 2023, 2003, 1037, 2742, 102]],
    "attention_mask": [[1, 1, 1, 1, 1, 1]],
    "labels": [1]
}

train_dataset = Dataset.from_dict(dummy_data)

print("Dummy Dataset Created Successfully")

# Training arguments
training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,

    warmup_steps=100,

    weight_decay=0.01,

    logging_steps=50,

    save_strategy="no",

    load_best_model_at_end=False,

    report_to="wandb",

    run_name="distilbert-run-1"
)

print("Training Arguments Created Successfully")

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=train_dataset,

    compute_metrics=compute_metrics
)

print("Trainer Created Successfully")

import json
import wandb

from sklearn.metrics import classification_report

# Run evaluation
eval_results = trainer.evaluate(eval_dataset=train_dataset)

print(eval_results)

# Log metrics to W&B
wandb.log({
    "final/loss": eval_results["eval_loss"],
    "final/accuracy": eval_results["eval_accuracy"],
    "final/f1": eval_results["eval_f1"],
})

# Predictions
preds = trainer.predict(train_dataset).predictions.argmax(-1)

# Labels
labels = [item["labels"] for item in train_dataset]

# Classification report
report = classification_report(
    labels,
    preds,
    output_dict=True
)

# Save report
with open("eval_report.json", "w") as f:
    json.dump(report, f, indent=2)

# Create W&B artifact
artifact = wandb.Artifact(
    "eval-report",
    type="evaluation"
)

artifact.add_file("eval_report.json")

wandb.log_artifact(artifact)

wandb.finish()

print("Task 5 Completed Successfully")

