# -*- coding: utf-8 -*-
"""task4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/kumar1984/task4-py.b1f840aa-59ac-4d48-822d-b457da959d34.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260519/auto/storage/goog4_request%26X-Goog-Date%3D20260519T114435Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D35bb1e1ef987406be2f350d81b9f38b6e11bbc29ec579ed7fc39fabeb886d998cbf75da188f9607fac1e73b96476b59facc93bb58bae9cfffc0c68650fc0e99c5445fe02e4c79b2e512980e5ec1aa0294fad722a5fbc94315ed967b7831589531a2496b8be4db8aa997b3b70871d667e21b2a5cf74300c7bba21742e4830b3467e597d63f124b6b6331501ad73e90db922077307db1597308956008eadbe408393a817ab29bb2cd3abb59f9c59cc5042c5e8cf070ea5629c5a29113ca7980557cf88ea1558a97065c8c4325444aa857b66ba48b6cab045a68cc3171d06b82ab13e256dcb364c972800f2fd2ffd94da9b975411bc7e825b664a03781e5638419e
"""

import torch
import wandb

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import accuracy_score, f1_score

model_name = "distilbert-base-cased"

tokenizer = DistilBertTokenizerFast.from_pretrained(model_name)

model = DistilBertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

print("Tokenizer and Model Loaded Successfully")

import wandb

wandb.login(
    key="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"
)

wandb.init(
    project="mlops-assignment2",
    name="distilbert-run-1"
)

print("WandB Initialized Successfully")

from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="weighted")
    }

print("Metrics Function Created Successfully")

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,

    warmup_steps=100,

    weight_decay=0.01,

    logging_steps=50,

    eval_strategy="no",

    save_strategy="no",

    load_best_model_at_end="False",

    report_to="wandb",

    run_name="distilbert-run-1"
)

print("Training Arguments Created Successfully")

from datasets import Dataset

dummy_data = {
    "input_ids": [[101, 2023, 2003, 1037, 2742, 102]],
    "attention_mask": [[1, 1, 1, 1, 1, 1]],
    "labels": [1]
}

train_dataset = Dataset.from_dict(dummy_data)

print("Dummy Train Dataset Created Successfully")

trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset= train_dataset,
    eval_dataset=None,

    compute_metrics=compute_metrics
)

print("Trainer Created Successfully")

trainer.train()

print("Model Training Completed Successfully")

results = trainer.evaluate(eval_dataset=train_dataset)

print(results)

print("Evaluation Completed Successfully")

