# -*- coding: utf-8 -*-
"""task6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/kumar1984/task6-py.504b63bf-19cd-46bf-9cc1-94f74ac1859d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260519/auto/storage/goog4_request%26X-Goog-Date%3D20260519T130221Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D72763f0db1976adc3d22225fbe955e18a51a222d129ce7f48296df6a15eb73ceeb3374e1e58a34bd707f683da861c8edb927695dff94dda0b1d527ec8b6a11244d08a122d32b449c476757e3f668c534903005d60ba71e28ea2270d95269915d41c7d2561d7e00dae4004680db4cc810c0b390e80f2dcf1a84439f201758233c17e9590777ccae40dfd0679671d05b68f0dcf46d86a6dd61e8d403fda0af305f6d7ec4018ec5e6357e5bfc1e455fe4a0f3a4f458159ce7bc60c314db6b1b4ea48b7af5015c402b2bff43bdef2bee12c28f71093f6a289043b829c753187fdd0f194f35959d6590c0b4a42088c3460bb9652fc3a7f9b4492fe9b258f477464a09
"""

!pip install huggingface_hub

from huggingface_hub import login

login(token="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")

print("Hugging Face Login Successful")

from transformers import DistilBertTokenizerFast
from transformers import DistilBertForSequenceClassification

model_name = "distilbert-base-cased"

tokenizer = DistilBertTokenizerFast.from_pretrained(model_name)

model = DistilBertForSequenceClassification.from_pretrained(model_name)

print("Model and Tokenizer Loaded Successfully")

repo_name = "sanjay-bert-model"

model.push_to_hub(f"sanjay-mlops/{repo_name}")

tokenizer.push_to_hub(f"sanjay-mlops/{repo_name}")

print("Model and Tokenizer Uploaded Successfully")

import wandb

wandb.init(project="task6-huggingface")

wandb.run.summary["hf_model_url"] = "https://huggingface.co/sanjay-mlops/sanjay-bert-model"

print("HF Model URL Logged Successfully")

